[DEVADV-324]Fixing cte_client_resources
thalescpl-io/terraform-provider-ciphertrust pull request #1
Opened 2024-11-13 05:13 UTC by manishkumar-thales

Fixing cte_client_resources for production ready

2024-11-13 14:42 UTC, anugram requested changes

2024-11-13 14:42 UTC, anugram commented on internal/provider/common/requests.go
> +func (c *Client) DeleteByID(ctx context.Context, method string, uuid string, url string, delbody []byte) (string, error) {
I would encourage using camel casing, delBody. Also instead of delBody, we might just have payload or body since we already know this body is part of the delete method.

2024-11-13 14:42 UTC, anugram commented on internal/provider/common/requests.go
> +func (c *Client) DeleteByID(ctx context.Context, method string, uuid string, url string, delbody []byte) (string, error) {
is there a possibility of method being anything else but Delete?

2024-11-13 14:42 UTC, anugram commented on internal/provider/common/requests.go
> +func (c *Client) DeleteByID(ctx context.Context, method string, uuid string, url string, delbody []byte) (string, error) {
Have you analyzed the impact of changing this method at other places. If this method is being used somewhere else, that will break.

2024-11-13 14:42 UTC, anugram commented on internal/provider/cte/resource_cte_client.go
> +	ctepasswdgenationmethod = []string{"GENERATE", "MANUAL"}
camel casing and spell errors

2024-11-13 14:42 UTC, anugram commented on internal/provider/cte/resource_cte_client.go
> +  	cteclienttype = []string{"FS", "CTE-U"}
camel casing

2024-11-13 14:42 UTC, anugram commented on internal/provider/cte/resource_cte_client.go
> +  				Required:    true,
this is required true only if a condition is met. so we should be handling it in the code below instead

2024-11-13 14:56 UTC, manishkumar-thales commented on internal/provider/common/requests.go
> +func (c *Client) DeleteByID(ctx context.Context, method string, uuid string, url string, delbody []byte) (string, error) {
yes for client its a part of PATCH

2024-11-14 16:33 UTC, anugram approved these changes
looks good

2024-11-14 16:40 UTC, merged