Added HSM ROT setup support for type Luna
thalescpl-io/terraform-provider-ciphertrust pull request #13
Opened 2024-11-27 07:55 UTC by om-shrirao

2024-11-27 14:54 UTC, anugram requested changes

2024-11-27 14:54 UTC, anugram commented on docs/resources/hsm_root_of_trust_setup.md
> +  conn_info    = "{\"partition_name\": \"kylo-partition\", \"partition_password\": \"sOmeP@ssword\"}"
instead of JSON string, we can make it a struct that will accept the params as key-value pair

2024-11-27 14:54 UTC, anugram commented on docs/resources/hsm_root_of_trust_setup.md
> +    host           = "172.20.32.11"
is it wise to put http or https here? or will it always be HTTPS

2024-11-27 14:54 UTC, anugram commented on docs/resources/hsm_root_of_trust_setup.md
> +- `initial_config` (Map of String) A free form JSON opaque blob. The expected content of this parameter depends on the specific HSM type used.
is it a JSON opaque blob or actual map type object in TF

2024-11-27 14:54 UTC, anugram commented on internal/provider/cm/resource_hsm_rot.go
> +			"conn_info": schema.StringAttribute{
same as above, instead of StringAttribute, a MapAttribute or SingleNestedAttribute

2024-11-27 14:54 UTC, anugram commented on internal/provider/cm/resource_hsm_rot.go
> +	resp.Diagnostics.AddError(
I like this, proper messaging, I can add this in other resources

2024-11-28 07:16 UTC, om-shrirao commented on docs/resources/hsm_root_of_trust_setup.md
> +  conn_info    = "{\"partition_name\": \"kylo-partition\", \"partition_password\": \"sOmeP@ssword\"}"
Okay, resolved it please check

2024-11-28 07:16 UTC, om-shrirao commented on docs/resources/hsm_root_of_trust_setup.md
> +- `initial_config` (Map of String) A free form JSON opaque blob. The expected content of this parameter depends on the specific HSM type used.
Resolved, it is the map type object in TF

2024-11-28 07:18 UTC, om-shrirao commented on internal/provider/cm/resource_hsm_rot.go
> +	resp.Diagnostics.AddError(
yes, it is good user experience

2024-11-28 07:23 UTC, om-shrirao commented on docs/resources/hsm_root_of_trust_setup.md
> +    host           = "172.20.32.11"
it needs just ip or hostname, (lunasatest1.lab or 172.20.32.11), no need to put http or https, it is handled internally by CM.

2024-12-02 14:35 UTC, anugram approved these changes

2024-12-03 04:18 UTC, merged